name: New master pull request webhook
on:
  pull_request:
    branches: [master]
    types: [opened]
jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
